### PR TITLE
[MM-23827] - Update NPS version

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
Update NPS plugin version

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-23827

### CODE REVIEW

**Comment by hanzei** [comment]
@nevyangelova Do you take of submitting the plugin to the [Marketplace](https://github.com/mattermost/mattermost-marketplace) or should I?

**Comment by nevyangelova** [comment]
@hanzei thank you for offering. I haven't done it before and not sure if I have the right permissions so you can submit it. Thank you :))

**Comment by hanzei** [comment]
@nevyangelova Done: https://github.com/mattermost/mattermost-marketplace/pull/63

**Comment by nevyangelova** [comment]
Thanks!

**Pull request merged**
