### PR TITLE
[MM-49594] Move CI/CD to Github Action

### PR DESCRIPTION
**Pull request by JulienTant**
#### Summary
Move from CircleCI to GH Actions.

We need someone with enough privilege on this repo to make those two new steps "mandatory" as right now the github tick is green when lint fails for example.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-49594

### CODE REVIEW

**Comment by JulienTant** [comment]
Dear reviewer, I do need someone with privilege on this repo to make those two "mandatory" as right now the github tick is green when lint fails for example

**Review by spirosoik — APPROVED** [review]
great work Julien!!

**Comment by marianunez** [comment]
I don't have much context on GH actions so I will remove my review here.

**Review by toninis — APPROVED** [review]
👍🏼

**Review by larkox — APPROVED** [review]

**Pull request merged**
