### PR TITLE
[MM-15755] fix link to admin console > integrations

### PR DESCRIPTION
**Pull request by cpanato**
fix the link to the new url for admin_console > integrations

### CODE REVIEW

**Comment by hmhealey** [comment]
@cpanato Does this need any further changes? There was some discussion in the R&D meeting last week that we were going to move these pages again

**Comment by hmhealey** [comment]
@wiersgallak The `{.SiteURL}` is only needed in the first case since that's for an email notification, so it needs the absolute link. The second case is inside the web app, so it knows that the link is relative to the root of the web app.

**Comment by cpanato** [comment]
@hmhealey i will check tomorrow

**Comment by hmhealey** [comment]
I've updated the links to match the latest version of the web app. We should really try to maintain backwards compatibility on these in the future to avoid the links accidentally breaking again

**Pull request merged**
