### PR TITLE
Add icon

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Add icon for Plugin Marketplace
Screenshot from 2020-04-01 18-24-52

#### Ticket Link
https://community-release.mattermost.com/core/pl/193whekzet87zdy83bqqxhd87c

### CODE REVIEW

**Comment by hanzei** [comment]
FYI: There has to be a new release of the plugin for the changes to take effect. @hmhealey @esethna Thoughts on cutting a new release soon?

**Comment by hmhealey** [comment]
I'd be up for cutting a new release, but I think we'd want to tie it to the MM version since this is a special case for a plugin. It might be too late to do it for 5.22 at this point though, so it might have to be 5.24

**Comment by hmhealey** [comment]
I created a ticket and tentatively assigned it to 5.23. It's been quite a while since we last updated the bundled NPS plugin, but there have only been some minor changes and dependency upgrades since then.

**Comment by esethna** [comment]
@hmhealey ^

**Pull request merged**
