### PR TITLE
MM-28520-Update NPS plugin version

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Update NPS plugin version

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28520

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]

**Review by hanzei — CHANGES_REQUESTED** [review]
Let's wait until https://github.com/mattermost/mattermost-plugin-nps/pull/74 is merged

**Review by hanzei — APPROVED** [review]
LGTM

**Comment by hanzei** [comment]
@sbishel Are you also taking care of 
1. Cutting the release
2. Updating the bundled version in the server
3. Pushing the release to the Marketplace?

Let me know if you have any questions.

**Comment by sbishel** [comment]
And...I just merged it. 
@ogi-m Sorry, I merged prematurely. But I think its ok. I won't cut the release until you approve.

**Comment by sbishel** [comment]
> @sbishel Are you also taking care of
> 
> 1. Cutting the release
> 2. Updating the bundled version in the server
> 3. Pushing the release to the Marketplace?
> 
> Let me know if you have any questions.

I'm planning on doing 1 and 2. But could definitely use some help on 3.

**Comment by hanzei** [comment]
@sbishel Once you cut the release using `/mb cutplugin` on the Community server you will get a response guiding you to how to add the release to the Marketplace.

**Comment by ogi-m** [comment]
@sbishel Approved from QA perspective, but I don't have the permissions in this repo so I can't update the labels

**Pull request merged**
