### PR TITLE
Add profile image for bot

### PR DESCRIPTION
**Pull request by hmhealey**
Finding static files from the plugin is hard when they need to be accessed from the server-side code, so instead of fighting with that, I just wrote the profile image into the plugin's Go code

### CODE REVIEW

**Comment by hanzei** [comment]
You can use [`GetBundlePath()`](https://developers.mattermost.com/extend/plugins/server/reference/#API.GetBundlePath) to get the root of your bundle directory.

The code would look like this:
	
```go
	bundlePath, err := p.API.GetBundlePath()
		if err != nil {
			return errors.Wrap(err, "failed to get bundle path")
		}

		profileImage, err := ioutil.ReadFile(filepath.Join(bundlePath, "assets", "somefile.png"))
		if err != nil {
			return errors.Wrap(err, "failed to read profile image")
		}

		if appErr := p.API.SetProfileImage(bot.UserId,, profileImage); appErr != nil {
			return errors.Wrap(err, "failed to set profile image")
}
```

**Comment by hmhealey** [comment]
@hanzei Oh, cool. I didn't know that existed. We can look into using that later, but since we're cutting it close with getting this in for 5.10, I don't think it needs to be changed now.

**Comment by hanzei** [comment]
@hmhealey Would you mind if I take care of this and use `GetBundlePath()`? Or do you want to get this in as quickly as possible?

**Comment by hmhealey** [comment]
I'd definitely appreciate it, but I'd prefer to get this in and have that as a separate PR for after 5.10. I'm trying to be strict on the feature submission deadline here so that QA has plenty of time to test this before release.

**Pull request merged**
