### PR TITLE
[MM-46440]: Change Mattermost logo from grey to black

### PR DESCRIPTION
**Pull request by emmyni**
#### Summary

Changed Mattermost logo from grey to black.

Related PRs: 
https://github.com/mattermost/mattermost-server/pull/21272
https://github.com/mattermost/customer-web-server/pull/939

Note: The CI checks are not passing but it might be related to the fix in this [PR](https://github.com/mattermost/mattermost-plugin-nps/pull/91)

#### Ticket Link

[MM-46440](https://mattermost.atlassian.net/browse/MM-46440)

### CODE REVIEW

**Review by marianunez — APPROVED** [review]

**Review by JulienTant — APPROVED** [review]
LGTM @emmyni

**Review by AGMETEOR — APPROVED** [review]

**Comment by annelieseklein** [comment]
@emmyni did marketing tell you exactly what color to put it in or just #00000? The color we are using on the product design side is : 3F4350

**Comment by emmyni** [comment]
> @emmyni did marketing tell you exactly what color to put it in or just #00000? The color we are using on the product design side is : 3F4350

@annelieseklein They didn't mention the specific hex code colour to use. They only said to have white borders instead of the light grey ones (#F3F3F3). Also, isn't #3F4350 a grey colour too?

**Comment by marianunez** [comment]
> > @emmyni did marketing tell you exactly what color to put it in or just #00000? The color we are using on the product design side is : 3F4350
> 
> @annelieseklein They didn't mention the specific hex code colour to use. They only said to have white borders instead of the light grey ones (#F3F3F3). Also, isn't #3F4350 a grey colour too?

For reference this is the logo that is being used and it seems to be the same as other places in Mattermost webapp as well 

logo

**Comment by emmyni** [comment]
@annelieseklein @marianunez Sorry I got mixed up, I thought that we were talking about the email borders for some reason. Yeah, it only mentions to switch it to the Black Mattermost logo.

**Pull request merged**
