### PR TITLE
Bump version to 1.2.0

### PR DESCRIPTION
**Pull request by marianunez**
#### Summary

Bump version to v.1.2.0 to include mainly: 

- [Rename Surveybot to Feedbackbot and add a feedback item in the "?" menu] https://github.com/mattermost/mattermost-plugin-nps/pull/87

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-42059

### CODE REVIEW

**Review by JulienTant — APPROVED** [review]
LGTM, the only other occurrence that I found is in the `mattermost-server` repository:

https://github.com/mattermost/mattermost-server/blob/master/Makefile#L129

**Review by hanzei — COMMENTED** [review]
LGTM :+1:

**Review by hanzei — APPROVED** [review]

**Comment by marianunez** [comment]
> LGTM, the only other occurrence that I found is in the `mattermost-server` repository:
> 
> [https://github.com/mattermost/mattermost-server/blob/master/Makefile#L129](https://github.com/mattermost/mattermost-server/blob/master/Makefile?rgh-link-date=2022-03-04T00%3A03%3A36Z#L129)

Yes, will be opening a PR to update the pre-packaged plugins shortly 👍

**Review by stevemudie — APPROVED** [review]
@marianunez The plugin worked as expected thanks to some help I received from @DHaussermann and you can check it out below if you'd like.

https://npm-test-server.test.mattermost.cloud/nps/channels/town-square
(standard sysadmin credentials)

**Comment by marianunez** [comment]
This feel off my radar 🤦‍♀️ Merging to complete the release process now.

**Pull request merged**
