### PR TITLE
Close client after deactivation

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
Close telemetry client after deactivation

#### Ticket Link
None

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
LGMT.

Should we update the docs in https://pkg.go.dev/github.com/mattermost/mattermost-plugin-api@v0.0.11/experimental/telemetry?tab=doc?

**Comment by larkox** [comment]
At the moment we don't have a proper "implementation example" in place. In such example we should note that:
- We should start the client on activation
- Update the tracker on configuration change
- Close the client on deactivation

Not sure how or where to put that in the godoc documentation. Any idea?

**Comment by hanzei** [comment]
godoc can contain arbitrary code. I would recommend placing the examples in the root package documentation. https://pkg.go.dev/github.com/fluhus/godoc-tricks?tab=doc is a nice resource for godoc.

**Review by jfrerich — APPROVED** [review]

**Comment by DHaussermann** [comment]
@larkox this seems simple enough but, I'm not sure how to test this. It would seem the plugin stops sending telemetry regardless. So, would I confirm if this telemetry client is still running?

**Comment by larkox** [comment]
@DHaussermann Right now I don't know any way to test this neither.

**Comment by hanzei** [comment]
@DHaussermann Would you be fine merging this PR as it is?

**Review by DHaussermann — APPROVED** [review]
Tested and passed

I did regression test the telemetry with NPS and it is still working as expected. 
No other functional testing is applicable here.

LGTM!

**Comment by DHaussermann** [comment]
@hanzei and @larkox I cannot adjust labels in this repo but reviews are complete.

**Pull request merged**
