### PR TITLE
[MM-18640] Update mattermost-redux

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

This repo is already manually using the CSRF token, but I figure all of the plugins should use it the same way (through the `mattermost-redux` repo).

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-18640

#### QA Steps

- Set `ServiceSettings.ExperimentalStrictCSRFEnforcement` to true in the server's config.json

- When refreshing the page, there should be a network call to `/plugins/com.mattermost.nps/api/v1/connected`. It should return a 200.

### CODE REVIEW

**Comment by mickmister** [comment]
I'm not sure how to solve this error in the ci output:

```
go: github.com/mattermost/mattermost-server@v0.0.0-20190822022538-11b0a20d7df9 requires
	willnorris.com/go/imageproxy@v0.9.0 requires
	cloud.google.com/go@v0.37.1 requires
	go.opencensus.io@v0.19.1 requires
	google.golang.org/genproto@v0.0.0-20181219182458-5a97ab628bfb requires
	google.golang.org/grpc@v1.16.0 requires
	github.com/golang/lint@v0.0.0-20190227174305-8f45f776aaf1: invalid pseudo-version: does not match version-control timestamp (2018-12-17T17:45:47Z)
make: build/bin/manifest: Command not found
build/setup.mk:13: *** "Cannot parse id from plugin.json".  Stop.
Exited with code 2
CircleCI received exit code 2
```

**Comment by cpoile** [comment]
Me neither. Ask on Developer Build System?

**Comment by hanzei** [comment]
PR to fix CI: https://github.com/mattermost/mattermost-plugin-nps/pull/54

**Comment by mickmister** [comment]
@hanzei Your link points to this PR

**Comment by hanzei** [comment]
@mickmister Fixed

**Pull request merged**
